### ISSUE TITLE
Images in articles

### ISSUE THREAD

**Issue by jkimbo** [FelixOnline/FelixOnline#102]
Most of the images in articles are using the old format of `/inc/timthumb.php?` which should be replaced by `img.felixonline.co.uk`. A simple script to replace all instances of it should be enough but in future the image should be generated on dynamically rather than hardcoded into the text. We could implement some kind of unique tag to use in the content that could be interpreted on render and replaced by the image.

**Comment by lsproc** [comment]
Now that we have switched to Sir Trevor for articles, this is trivial.

**Comment by lsproc** [comment]
DONE

Upon conversion of article text to Sir Trevor format (which is JSON and Markdown if you are curious) the images are now converted into JSON. This JSON refers to the database image ID and the caption/attribution as specified in the HTML.

Going forward Sir Trevor will be configured to let you add images using this new format and will keep the database in synch in terms of the attribution and so forth.
