### ISSUE TITLE
Longer comments

### ISSUE THREAD

**Issue by jkimbo** [FelixOnline/FelixOnline#12]
After just witnessing one person comment on an article 5 times I think that we should probably increase the size of the comment box. However we obviously don't want essays so we could do something similar to what Facebook does and crop off a comment after a certain word limit with a "Read more" link that would expand the comment for people who wanted to read more.

**Comment by lsproc** [comment]
WOOOOOOOOO DONE!

Apart from the read more but not sure if we need that just now, will monitor
