### ISSUE TITLE
New Look Felix Site

### ISSUE THREAD

**Issue by txsl** [FelixOnline/FelixOnline#216]
As per Philippa's drawings. (I hope everyone has them).

Widgets to add include:
* Latest Issue
* Horoscopes
* "Overheard in the Office"
* Recent Comments
* Trending articles

Also need the ability to add a sponsor banner at the bottom of each page, and section sponsors.

This is the priority for launch before the beginning of term.

**Comment by lsproc** [comment]
The redesign has been completed so I will now close this - I am aware there are things we haven't done but I'd rather we discussed those again now we have an idea of where we are at with the website.
