### ISSUE TITLE
Commenting Engine Updates

### ISSUE THREAD

**Issue by txsl** [FelixOnline/FelixOnline#217]
After discussion, decision taken to keep comments managed in house (not move to Disqus or similar). 

The main modifications to the comment engine are:
* Get spam reduction in place as Askimet seems to have broken (lets everything through?)
* 'Report Abuse' button/feature must be implemented.

Second priority before Freshers' launch.

**Comment by lsproc** [comment]
Well our change to auto close comments worked a treat - akismet is within limit now and working a treat! All that remains is to implement Report Abuse and Email Verification - the latter will likely wait until after look at tidying up the database and comment code.

**Comment by entrepreneurj** [comment]
Yay!

Joe Letts

**Comment by entrepreneurj** [comment]
Great stuff :) 

Joe Letts
