### ISSUE TITLE
Ad serving engine

### ISSUE THREAD

**Issue by txsl** [FelixOnline/FelixOnline#219]
An advertising engine. Specs (for a complete system):

* Upload image of specified size (and link)
* Select which sections of website it will appear
* Select how many views the ad will receive.
* Image is served to real users (i.e. not served to bots).
* Image is no longer served once desired number of views have been served.
* Would be great to track clicks too

**Comment by lsproc** [comment]
@txsl  If you have 5 mins could you give me a hand with this and see if there is a good way to detect bots?

**Comment by lsproc** [comment]
Model and tests written, still to do controllers and views

**Comment by lsproc** [comment]
Controller done all thats left are the views to show the adverts

**Comment by lsproc** [comment]
Done
