### ISSUE TITLE
media sentry server

### ISSUE THREAD

**Issue by entrepreneurj** [FelixOnline/FelixOnline#225]
Do you still want to use sentry? I'm going to retire my sentry server at some stage in the near future, but @lukegb has indicated he may make a media-wide sentry server if that suits?

**Comment by lsproc** [comment]
Hey guys what was the outcome of this?

**Comment by entrepreneurj** [comment]
I don' t know if we got the historical records integrated, but I think I left a copy on gears.media.su.ic.ac.uk.  is sentry.media. still up and running @lukegb? Maybe they could just start a new project if the data is hard to export. I doubt there's too much of note!

**Comment by lukegb** [comment]
Historical records didn't get copied over and Sentry isn't currently running (since there weren't any projects and I was trying to import a dump, it didn't get added to start-on-reboot) - if there's interest in it I can easily revive it.

**Comment by lsproc** [comment]
Please! Felix used to send fatal errors to Sentry but it was always a little dodgy. Im rewriting the exception system at the moment (one simple fix turned out to be a rewrite) and want to get sentry working properly this time.

**Comment by lukegb** [comment]
Sentry's back up and running. It's now using Media LDAP for authentication so you should just be able to log in.

**Comment by lsproc** [comment]
Thank you!

**Comment by lsproc** [comment]
I have configured it for Felix. I didnt know if you wanted it for other media things so I just created a Felix organisation and team, i don’t mind at all if you want to rename the org to icu media group and put other things in it or anything :)

**Comment by lukegb** [comment]
I'm not really sure. We could just use that organisation for everything but it might be best to have them distinct, I dunno...

For now, let's leave it as is.

I've requested an SSL certificate for sentry.media.su.ic.ac.uk from ICT, so hopefully that'll happen once the College closure period is concluded.

**Comment by lsproc** [comment]
I don’t really know how these things work but basically - I don’t mind :)

But sure thing. Thanks - I will get into integrating Felix into Sentry once my accidental minor overhaul of the felixonline framework is complete ;)

**Comment by lsproc** [comment]
DONE! Thanks @lukegb 

@entrepreneurj felix no longer uses your sentry :)
