### ISSUE TITLE
Remove timthumb

### ISSUE THREAD

**Issue by lsproc** [FelixOnline/FelixOnline#242]
Now that we have a new way of storing images we can be rid of timthumb as it is no longer supported.

Suggest switching to a gd/imagick based backend which may even let us convert CMYK pics to RGB.

**Comment by jkimbo** [comment]
https://github.com/thumbor/thumbor is a pretty great self hosted solution btw

**Comment by lsproc** [comment]
Good to hear from you! :) Thanks for the tip, I will take a look.

**Comment by jkimbo** [comment]
No worries! Pleasantly surprised to see lots of activity on here again :smile:

**Comment by lsproc** [comment]
Replaced with new imagick based script as this allows for dynamic conversion of non-RGB images to RGB which is essential for Felix these days (a lot of CMYK photos are being uploaded) and sadly Thumbor doesn't seem to get on well with CMYK photos.
